Implementation For Yield Offering Related APIs
ovalfi/go-sdk pull request #3
Opened 2022-09-02 12:06 UTC by leonardchinonso

##Implementation
- Added models for all yield related data objects
- Added methods in the RemoteCall interface to facilitate yield related requests
- Added an example package to test remote calls

##Paired With
CC @odetolakehinde

2022-09-02 12:18 UTC, odetolakehinde commented on api/yield.go
> +		fL.Info().Str("error_code", fmt.Sprintf("%d", res.StatusCode())).Msg(string(res.Body()))
can we have the `error_code` to be in constants? `model.LogErrorCode`

2022-09-02 12:58 UTC, odetolakehinde approved these changes

2022-09-02 14:26 UTC, odetolakehinde commented
@wharleyinc @azeezlala

2022-09-02 15:49 UTC, wharleyinc reviewed
@odetolakehinde looks good to me

2022-09-02 16:17 UTC, azeezlala requested changes

2022-09-02 16:17 UTC, azeezlala commented on api/yield.go
> +		SetHeader("X-Idempotent-ID", c.idempotentID.String()).
No needed sha

2022-09-05 09:13 UTC, odetolakehinde approved these changes

2022-09-05 09:38 UTC, azeezlala approved these changes
LGTM

2022-09-05 09:43 UTC, merged