feat: update error response on getExchangeRate details
ovalfi/go-sdk pull request #32
Opened 2023-01-25 14:02 UTC by wharleyinc

- We want to return a more descriptive error response on a call to get withdrawal rates `this service is currently unavailable. Please try again later`.

2023-01-25 16:00 UTC, odetolakehinde requested changes
This should be across all endpoints. And also, can we see an example?

2023-01-26 07:59 UTC, wharleyinc commented
> * We want to return a more descriptive error response on a call to sdk endpoints.
> 
> Sample error response from
> 
> ```
>   apiCalls.FiatWithdrawal(context.Background(), model.WithdrawalRequest{
> 		CustomerID:      uuid.MustParse("9f40fb69-64e3-4d23-853a-0243af155427"),
> 		Reference:       "polkj",
> 		Amount:          10,
> 		YieldOfferingID: uuid.MustParse("42ee80d8-2a95-419c-aad1-5643d306948e"),
> 		PayoutCurrency:  "NGN",
> 		BankDetail: &model.BankDetail{
> 			BankCode:      "057",
> 			AccountNumber: "2209276822",
> 		},
> 	})
> ```
> 
> will return possible error responses like below
> 
> * `this service is currently unavailable. Please try again later`.
> * `Customer does not exist.`
> 
> ref https://ovalfi.atlassian.net/browse/PAP-199

Here boss @odetolakehinde

2023-01-26 08:31 UTC, odetolakehinde approved these changes

2023-01-26 09:24 UTC, sheygs13 approved these changes

2023-01-26 09:31 UTC, itebababatunde approved these changes

2023-01-26 10:02 UTC, merged