Implementation For Withdrawal Related APIs
ovalfi/go-sdk pull request #7
Opened 2022-09-05 21:06 UTC by wharleyinc

##Implementation

Added models for all yield related data objects
Added methods in the RemoteCall interface to facilitate yield related requests
Added an example package to test remote calls
##Paired With
CC @odetolakehinde

2022-09-05 23:04 UTC, odetolakehinde requested changes
Is this the only withdrawal function?

2022-09-05 23:04 UTC, odetolakehinde commented on api/withdrawal.go
> +	"net/http"
not go formatted.

2022-09-05 23:04 UTC, odetolakehinde commented on model/model.go
> +	"time"
this too.

2022-09-06 04:53 UTC, wharleyinc commented
> Is this the only withdrawal function?

According to the docs, we only have this. But if it is required, I can add other functions.

2022-09-06 08:45 UTC, odetolakehinde submitted a review, later dismissed

2022-09-06 08:49 UTC, azeezlala approved these changes

2022-09-06 10:02 UTC, odetolakehinde commented on api/withdrawal.go
> +		Float64("amount", request.Amount).
update using the interface method.

2022-09-06 12:19 UTC, odetolakehinde approved these changes

2022-10-06 14:13 UTC, Dark-Vinci approved these changes

2022-10-06 14:14 UTC, merged